### ISSUE TITLE
Google fonts does not work when offline

### ISSUE THREAD

**Issue by exarkun1298** [suhrmann/Anno-1800-Calculator#10]

**Comment by suhrmann** [comment]
[Install Material Design Icons [Vuetify doc]](https://vuetifyjs.com/en/framework/icons#install-material-design-icons) doesn't work - somehow -_-

It's not enough to follow this guide - the icons in the Vuetify components will not be changed (e.g. `mdi-exclamation` instead of `priority_high`)

**Comment by suhrmann** [comment]
Seems like the documenation for installing Icons in Vuetify lacks lots of details.
The documentation will improve in Vuetify version 2

**Comment by suhrmann** [comment]
Font-Fix described in commit b0e99e3ab6c6e24a3e3f91e6f6df15542e939bb7 :

I reinstalled The Vue plugin ´´vue-cli-plugin-vuetify´´ (to be used in *Vue UI*) and configured it manually to include fonts (for use with electron).
Then I had to fix the broken "Material Icons" and replace them with new "Material Design Icons".
