### ISSUE TITLE
Investors do not increase consumption of cigars

### ISSUE THREAD

**Issue by GrumpyCatastrophe** [suhrmann/Anno-1800-Calculator#13]
In game cigars are used by investors and obreros. In calculator, investors do not increase consumption of cigars, while obreros do. Most likely connected to the fact that cigars are both basic and luxury items.
![cigars](https://user-images.githubusercontent.com/26677978/57587569-32dbd780-7507-11e9-843a-e3dcd8b8e08a.jpg)

**Comment by suhrmann** [comment]
Thank you for the issue. We weren't aware that cigars are basic and luxury. We are currently investigating the consequences for the calculator.

**Comment by suhrmann** [comment]
Should be fixed by commit 85825b6effa32ae7f8ad9e1156eed6b6c2c3f4e1

Cigars now appear twice in the table: Once as basic demand for investors and second as luxury demand for obreros.

@exarkun1298 @xenonisbad In case you would rather see only one (summed up) entry for cigars in the table, please let me know.

**Comment by xenonisbad** [comment]
Consumption looks good now, thank You for quick fix.  Separate occurrences for luxury and basic cigars are completely fine in consumption column, if anyone need it, adding those two values will be super easy, everybody can do it in their head. Good idea with pop-up message.

However there is a problem when it comes chains efficiency. We see that we need X% efficiency on x cigars chains and Y% efficiency on y cigar chains.  X% and Y% cannot be easily added, and we have to choose efficiency for whole island, so separate values here meaningless. Unless of course we have separate cigar production chains on two islands. I don't use those values, but I guess many people would.

Conclusion: the best would be to somehow combine appearance of cigars in table when consumable are not filtered. I doubt it will be as easy fix though.

Btw. I just checked that there is missing cigar production for investors in "Production Chains".

**Comment by suhrmann** [comment]
Investor's cigars bug fixed. 
Now still an enhancement

**Comment by suhrmann** [comment]
-> #25
