### ISSUE TITLE
Store selected production chain persistent

### ISSUE THREAD

**Issue by suhrmann** [suhrmann/Anno-1800-Calculator#14]
Issue #11 showed that simply storing the IDs of word, population and product is not enough to store the currently selected production chain persistent.

**Comment by exarkun1298** [comment]
fixed in 74e2eec5db36d580b8e6441dbbf054b17d622618
Before persistent VueX state the production chain object had to be re-initialized by a vue-router navigation guard on every reload.
Since the state is now persistent, a simple default value in the VueX store is sufficient
