### ISSUE TITLE
Ability to change number of residents per house

### ISSUE THREAD

**Issue by LePheel** [suhrmann/Anno-1800-Calculator#18]
I've modded my game to have different residents per house than the native game. Is there a way I could tweak your calculator to account for this? If there's somewhere that I can change in the source code, and rebuild (using the desktop app), that would be great, but I don't know how or if that's possible.

Thanks!

**Comment by tluderer** [comment]
Thanks for your suggestion! :)

If I understand you correctly, you would like to adjust the amount of e.g. how many farmers fit into a farmers house (default: 10).

Currently the calculator does not offer the feature to display the required amount of houses.

**Comment by suhrmann** [comment]
Added option to input population directly or via residence.
You can adjust the calculator for your mod by changing the values in [``residence.json``](https://github.com/suhrmann/Anno-1800-Calculator/blob/master/src/data/residence.json)

**Comment by LePheel** [comment]
Thanks for such a quick update! I'm going to play around with trying to build a custom version, but if I can't figure that out this will work too! Of all the calculators, this is my favorite :D
