### ISSUE TITLE
Production Chains - Workforce demand - Engineers

### ISSUE THREAD

**Issue by Arkentus** [suhrmann/Anno-1800-Calculator#19]
**Fail to count workforce demand : Engineers ONLY**
In production chains tools, engineers count is false 

- 2 Test exemple (Light Bulb Factory & Cab Assembly Line)
- I've check your producers.json, is correct

_________________________________
Test 1 : Light Bulb Factory
![ampoule](https://user-images.githubusercontent.com/25131967/63646730-bf598100-c717-11e9-835f-5efd26eca958.png)

Light Bulb Factory at 150 Engineers => 2x => 300 Engineers 
Filament Factory at 150 Engineers => 2x => 300 Engineers

**we need 600 engineer instead of the 550 give by the tool**

![ampoueUsine](https://user-images.githubusercontent.com/25131967/63646783-8ec61700-c718-11e9-9610-aa02b2780585.png)
![filamentUsine](https://user-images.githubusercontent.com/25131967/63646785-908fda80-c718-11e9-80d1-2bcaa56d7e73.png)
_________________________________
_________________________________
Test 2 : Cab Assembly Line
![voiture](https://user-images.githubusercontent.com/25131967/63646803-cf259500-c718-11e9-98ab-2b6f7092415f.png)

Cab Assembly Line at 500 Engineers => 4x => 2000 Engineers 
Motor Assembly Line at 250 Engineers =>6x => 1500 Engineers
Coachmakers at 150 Engineers => 8x => 1200 Engineers

**we need 4700 engineer instead of the 4900 give by the tool**

![screenshot_2019-08-25-08-54-26](https://user-images.githubusercontent.com/25131967/63646836-40654800-c719-11e9-992e-c62bc776c0c3.jpg)
![screenshot_2019-08-25-08-54-30](https://user-images.githubusercontent.com/25131967/63646839-44916580-c719-11e9-8a77-b345fa1ea123.jpg)
![screenshot_2019-08-25-08-54-28](https://user-images.githubusercontent.com/25131967/63646846-5541db80-c719-11e9-8814-e5e8790f5c48.jpg)
_________________________________
Thx for your work !!

**Comment by tluderer** [comment]
Hey, thank you for your detailed issue :) as stated in the other one, sorry for the delay -> holidays :)

**Light Bulb Factory**
> we need 600 engineer instead of the 550 give by the tool
Right. The data of the filament factory was wrong -> fixed

**Cab Assembly Line**
> we need 4700 engineer instead of the 4900 give by the tool
Correct - the Copper Mine data was wrong, 100 engineers per mine sneaked in :)

both problems fixed in f157120bd0a724936e5061d2052bdf3959d2d6e6

Thank you for your attentiveness :)
