### ISSUE TITLE
Input cells to small, Resident Demand

### ISSUE THREAD

**Issue by StingMcRay** [suhrmann/Anno-1800-Calculator#22]
Hello dear creators of the calculator,

I noticed that the input cells you use on the Resident Demands (for inhabitants only) only show 4 digits, while there are a lot of players that need 5 or 6 digits
For the houses input 4 should be good, but 5 would better i think

Regards

**Comment by StingMcRay** [comment]
Hmm... scaling it is 
So, when i use my browser on a smaller window mode then the input cells are to small....

**Comment by suhrmann** [comment]
I consider your issue now as solved.
