### ISSUE TITLE
Invalid Production Chain Ratio of Hibiscus Tea

### ISSUE THREAD

**Issue by AshamanX** [suhrmann/Anno-1800-Calculator#27]
Hi,

Thanks a lot for the amazing calculator and your effort into it!
I thiunk, I found a minor bug.

The production chain on your website is for the hibiscus tea seems not to be correct.
Also the calculator regarding this resource seems to be incorrect.

See the following link to the correct ratios.
https://anno1800.fandom.com/wiki/Production_chains#Hibiscus_Tea

Best!

**Comment by suhrmann** [comment]
With fixed CI/CD the changes are now live on Website and App Release
