### ISSUE TITLE
Suggestion: houses instead of amount of people

### ISSUE THREAD

**Issue by Joe78man** [suhrmann/Anno-1800-Calculator#32]
The calculator is easy to read (I'm pretty new to the game) and very complete, BUT, I see the same flaw I saw in almost all Anno xxxx calculators I used. In all of them you must enter the amount of population and in my opinion is the incorrect approach. I don't build people, I build houses, I want to know how many houses of each type I need,  
It's not very usefull to have a calculator if then I have to calculate by myself how many houses of each type I need to house that amount of farmers-workers, etc.
How about we enter the amount of houses of each type and the calculator multiplies the houses by the max occupancy and then calculates the resources?

Best of whishes!

**Comment by tluderer** [comment]
Hey Joe,

if I understand you correctly, you want to display the necessary houses on the Production Chains page directly?
Good Idea! I'd implement a switch to toggle between pop and houses - so people can use what they like.

Though you can currently use the suggested functionality. Its not as direct as you might want, but you can use it as a workaround till then.

Choose your Production Chain.
Then you can click on the "Add to Demands" button on the top right corner of the page.
You will be taken to the Resident Demand Page.
The you can Switch to "Residence"-Mode to calculate the houses you need to build.

**Comment by Joe78man** [comment]
Hey! thanks for the prompt response. I did found the residence mode after checking more deeply and does do the trick. Thanks!
I remember I ended up making my own table in excel for Anno 1404 where I'd enter the amount of houses and it would calculate the needed industries (not the production but the amount of production buildings) to satisfy the demand of all level of population. I think the residense mode in your calculator does this well enough.

Despite the numbers are good I think what matters is knowing how many of each buildings you need and not the actual production value, many times people focus on the numbers but forget the "customer" needs to know how many grain farms they need instead of checking the production and calculating how many they should build. It would be interesting if it shows the different possibilities (2 farms / 1 farm +tractor, and such).

Keep up the good work and thanks again for your reply
________________________________
De: Tobias Luderer <notifications@github.com>
Enviado: sábado, 23 de enero de 2021 21:25
Para: suhrmann/Anno-1800-Calculator <Anno-1800-Calculator@noreply.github.com>
Cc: Joe78man <joe78man@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [suhrmann/Anno-1800-Calculator] Suggestion: houses instead of amount of people (#32)


Hey Joe,

if I understand you correctly, you want to display the necessary houses on the Production Chains page directly?
Good Idea! I'd implement a switch to toggle between pop and houses - so people can use what they like.

Though you can currently use the suggested functionality. Its not as direct as you might want, but you can use it as a workaround till then.

Choose your Production Chain.
Then you can click on the "Add to Demands" button on the top right corner of the page.
You will be taken to the Resident Demand Page.
The you can Switch to "Residence"-Mode to calculate the houses you need to build.

**Comment by suhrmann** [comment]
Issue is solved. Remaining feature is in new issue
