### ISSUE TITLE
Vulerability in Dependencies

### ISSUE THREAD

**Issue by Cahllagerfeld** [suhrmann/Anno-1800-Calculator#39]
I got  a Notification in my Fork from Dependency which says there are 2 vulerabilities in the following two dependencies: 
- electron
- highlight.js

Maybe a version bump has to be made for these dependencies.

**Comment by suhrmann** [comment]
Just merged 2 DependaBot PRs.

**Comment by suhrmann** [comment]
Merged all dependabot alerts
