### ISSUE TITLE
Tortilla production chain issue

### ISSUE THREAD

**Issue by Nicolas0301** [suhrmann/Anno-1800-Calculator#4]
Hi, the calculator indicates that four cattle farms are needed to supply one tortilla maker. Only two are required.

**Comment by exarkun1298** [comment]
Tortillas were calculated wrong using the old world version of the Cattle Farm.
Data structure updated to distinguish between the different building versions. Issue fixed in ba14c19a2b66d1bf7355b2d26fa0967ba9e0b9ee.
