### ISSUE TITLE
[Add to demands] button: String concat instead of sum

### ISSUE THREAD

**Issue by suhrmann** [suhrmann/Anno-1800-Calculator#8]
Using the button multiple times, the value of population is calculated using string concatenation instead of summing up the values.

E.g.: 
1) 1x Production Chain: Wood (15 Farmers)
2) [Add to demands]
3) Demands Calculation: 15 Farmers
4) Doing 1 & 2 again results in 1515 Farmers

#javascriptisfun #typesafetysucks

**Comment by exarkun1298** [comment]
gladly, there is such a thing as type casting :)
resolved in commit 293ecd4de5eeb993c32eae4fe8894d19070038ea

**Comment by exarkun1298** [comment]
Variable type conversion remains to be an issue in certain cases

#javascriptisfun

**Comment by exarkun1298** [comment]
should be fixed now fad8b96e9f2c040e2fdce88b67b33d114380eb1e
