### ISSUE TITLE
Demands Table not working

### ISSUE THREAD

**Issue by exarkun1298** [suhrmann/Anno-1800-Calculator#9]
Demands Cards are working,
Demands Table is not.
Console output below

[Electron (PasteBin)](https://pastebin.com/n9cHt824)

Firefox:
`TypeError: "e.props is undefined"`
    `fn ResidentDemandsTable.vue:1`
    `VueJS 7`

​

**Comment by exarkun1298** [comment]
fixed by using Vue 2.5 syntax for slots
v-slot directive is Vue 2.6 only
commit c0c505c7f87f456117cc718e2433ff5ad61693cb

**Comment by suhrmann** [comment]
Commit, 
file / line [src/components/resident_demands/ResidentDemandsTable.vue L10](https://github.com/suhrmann/Anno-1800-Calculator/commit/c0c505c7f87f456117cc718e2433ff5ad61693cb#diff-2af00d6b2d034ff65d0d6b631e0d3a46L9)
